### ISSUE TITLE
5.0.1 release: no officeparser.py

### ISSUE THREAD

**Issue by GdBai** [zotero/zotero-word-for-mac-integration#13]
Hey guys,

I ran unpack_templates.sh and the log is as follows:
'../tools/officeparser/officeparser.py': [Errno 2] No such file or directory

I can't find officeparser.py in this repo... btw do I need to run this shell or should I just install the Zotero.dotm? I tried installing the dotm file directly into Word for Mac 2016, but the Add Bibliography button is not working, with prompt:

Zotero experienced an error updating your document.
(intermediate value)[command] is not a function

So what should I do? thx a lot

**Comment by adomasven** [comment]
We'll fix this, but it's not required for development.

If you're doing development, go to [our mailing list](https://groups.google.com/forum/#!forum/zotero-dev) for support.

Otherwise see [getting help](https://www.zotero.org/support/getting_help) support page and post on the forum. The tracker is for development use only.
